import { AnimatePresence, motion } from 'framer-motion';
import { useEffect, useMemo, useState, type ReactNode } from 'react';
import {
  Activity, ArrowRight, Bot, Check, ChevronRight, Command, Database, Download,
  FileText, GitBranch, Maximize2, MessageSquare, Network, Search, ShieldCheck,
  Sparkles, X, ZoomIn, ZoomOut,
} from 'lucide-react';
import { getAdapterMode, getHRIDAYAdapter } from '@/adapters';
import type { EngineeringFinding, WorkspaceId, WorkbenchTaskResult } from '@/adapters/types';

type ViewId = 'overview' | WorkspaceId;
type TaskState = 'idle' | 'running' | 'complete' | 'blocked';
type Asset = { id: string; x: number; y: number; type: string };

const ASSETS: Asset[] = [
  { id: 'P-101', x: 22, y: 51, type: 'Pump' }, { id: 'XV-201', x: 52, y: 51, type: 'Valve' },
  { id: 'V-202', x: 80, y: 51, type: 'Equipment' }, { id: 'PT-301', x: 39, y: 27, type: 'Instrument' },
  { id: 'DV-101', x: 39, y: 75, type: 'Drain' },
];
const WORKSPACES: Array<{ id: WorkspaceId; label: string; icon: typeof Network; description: string }> = [
  { id: 'engineering', label: 'Engineering', icon: GitBranch, description: 'Reasoning and maintenance context' },
  { id: 'pid', label: 'P&ID', icon: Network, description: 'Drawing and visual evidence' },
  { id: 'topology', label: 'Topology', icon: GitBranch, description: 'Governed connectivity' },
  { id: 'document', label: 'Documents', icon: FileText, description: 'Local document context' },
  { id: 'data', label: 'Data', icon: Database, description: 'Tables and analysis' },
  { id: 'evidence', label: 'Evidence', icon: ShieldCheck, description: 'Claims and provenance' },
  { id: 'artifact', label: 'Artifact', icon: Download, description: 'Deliverable draft' },
];
const QUICK_TASKS = [
  'Analyze P-101 and prepare an isolation summary',
  'Find the relevant SOP and check for procedural conflicts',
  'Prepare an evidence-backed approval note',
];

function Pill({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'neutral' | 'good' | 'warn' }) {
  const c = tone === 'good' ? 'border-emerald-400/20 bg-emerald-400/5 text-emerald-200' : tone === 'warn' ? 'border-amber-300/20 bg-amber-300/5 text-amber-200' : 'border-white/10 bg-white/[.03] text-zinc-400';
  return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 font-mono text-[9px] uppercase tracking-wider ${c}`}>{children}</span>;
}

function WorkspaceNav({ active, onChange }: { active: ViewId; onChange: (v: ViewId) => void }) {
  return <div className="grid grid-cols-2 gap-2 sm:grid-cols-4 xl:grid-cols-8">
    <button aria-current={active === 'overview' ? 'page' : undefined} onClick={() => onChange('overview')} className={`rounded-lg border px-3 py-2.5 text-left text-xs transition ${active === 'overview' ? 'border-cyan-300/30 bg-cyan-300/10 text-white' : 'border-white/10 bg-white/[.025] text-zinc-500 hover:text-white'}`}><span className="block font-medium">Overview</span><span className="mt-1 block text-[9px] text-zinc-600">Mission control</span></button>
    {WORKSPACES.map(({ id, label, icon: Icon, description }) => <button key={id} aria-current={active === id ? 'page' : undefined} onClick={() => onChange(id)} className={`rounded-lg border px-3 py-2.5 text-left text-xs transition ${active === id ? 'border-cyan-300/30 bg-cyan-300/10 text-white' : 'border-white/10 bg-white/[.025] text-zinc-500 hover:border-white/20 hover:text-white'}`}><Icon size={13} className="mb-1" /><span className="block font-medium">{label}</span><span className="mt-1 hidden text-[9px] text-zinc-600 xl:block">{description}</span></button>)}
  </div>;
}

function AssetInspector({ selected, onSelect }: { selected: string; onSelect: (id: string) => void }) {
  const role = ASSETS.find(a => a.id === selected)?.type ?? 'Asset';
  const observation = selected === 'P-101' ? 'Upstream suction isolation is unresolved.' : selected === 'XV-201' ? 'XV-201 is on the discharge path.' : 'No additional demo finding.';
  return <div className="rounded-xl border border-white/10 bg-[#070c0f] p-4"><div className="mb-3 flex items-center justify-between gap-3"><div><div className="font-mono text-[8px] uppercase tracking-[.2em] text-zinc-600">Selected asset</div><div className="mt-1 font-mono text-sm text-cyan-100">{selected}</div></div><Pill tone={selected === 'P-101' ? 'warn' : 'neutral'}>{role}</Pill></div><div className="space-y-2 text-[10px] leading-5 text-zinc-500"><div className="flex justify-between"><span>Class</span><span className="text-zinc-300">{role}</span></div><div><span>Observation</span><p className="mt-1 text-zinc-400">{observation}</p></div><p className="border-t border-white/5 pt-2 text-zinc-600">Selection is read-only; structured engineering truth remains outside the model.</p></div><div className="mt-3 flex gap-2">{selected !== 'P-101' && <button onClick={() => onSelect('P-101')} className="rounded-md border border-white/10 px-2.5 py-1.5 text-[9px] text-zinc-400 hover:text-white">Focus P-101</button>}</div></div>;
}

function PIDWorkspace({ selected, onSelect }: { selected: string; onSelect: (id: string) => void }) {
  const [zoom, setZoom] = useState(1);
  return <div className="grid gap-3 xl:grid-cols-[1fr_250px]"><div className="relative min-h-[440px] overflow-hidden rounded-xl border border-white/10 bg-[#071014]">
    <div className="absolute inset-0 opacity-30" style={{ backgroundImage: 'linear-gradient(rgba(90,220,220,.07) 1px, transparent 1px), linear-gradient(90deg, rgba(90,220,220,.07) 1px, transparent 1px)', backgroundSize: `${32 / zoom}px ${32 / zoom}px` }} />
    <div className="absolute left-4 top-4 z-10 rounded-md border border-amber-300/20 bg-black/60 px-3 py-2 font-mono text-[9px] text-amber-100">DEMO P&ID · SYNTHETIC VISUAL DATA</div>
    <div className="absolute right-4 top-4 z-30 flex gap-1"><button aria-label="Zoom out" onClick={() => setZoom(z => Math.max(.8, +(z-.1).toFixed(1)))} className="rounded-md border border-white/10 bg-black/60 p-2 text-zinc-400 hover:text-white"><ZoomOut size={13}/></button><button aria-label="Zoom in" onClick={() => setZoom(z => Math.min(1.5, +(z+.1).toFixed(1)))} className="rounded-md border border-white/10 bg-black/60 p-2 text-zinc-400 hover:text-white"><ZoomIn size={13}/></button><button aria-label="Reset zoom" onClick={() => setZoom(1)} className="rounded-md border border-white/10 bg-black/60 p-2 text-zinc-400 hover:text-white"><Maximize2 size={13}/></button></div>
    <svg viewBox="0 0 900 500" className="absolute inset-0 h-full w-full p-12" style={{ transform: `scale(${zoom})`, transformOrigin: 'center' }} aria-label="Synthetic P and ID drawing"><path d="M110 255 H790 M350 255 V100 M350 255 V405 M350 100 H530 M350 405 H530" fill="none" stroke="rgba(103,232,249,.35)" strokeWidth="4"/><path d="M250 255 H305 M410 255 H475 M580 255 H665" fill="none" stroke="rgba(255,255,255,.25)" strokeWidth="2" strokeDasharray="8 7"/></svg>
    {ASSETS.map(a => <button key={a.id} aria-label={`Select ${a.id}`} onClick={() => onSelect(a.id)} className="absolute z-20 -translate-x-1/2 -translate-y-1/2" style={{left:`${a.x}%`,top:`${a.y}%`}}><div className={`flex min-h-12 min-w-14 flex-col items-center justify-center rounded-lg border px-2 transition ${selected===a.id?'scale-110 border-cyan-300 bg-cyan-300/15 text-cyan-100 shadow-[0_0_30px_rgba(103,232,249,.15)]':'border-white/15 bg-[#0b171b] text-zinc-300 hover:border-cyan-400/50'}`}><span className="font-mono text-[10px] font-semibold">{a.id}</span><span className="text-[8px] uppercase tracking-wider text-zinc-600">{a.type}</span></div></button>)}
    <div className="absolute bottom-4 left-4 right-4 flex justify-between gap-2 font-mono text-[9px] text-zinc-600"><span>Sheet 01 · viewport D-7</span><span>{Math.round(zoom*100)}% · {selected}</span></div>
  </div><AssetInspector selected={selected} onSelect={onSelect}/></div>;
}

function TopologyWorkspace({ selected, onSelect }: { selected: string; onSelect: (id: string) => void }) {
  const nodes = [['P-101','17%','50%','Pump'],['XV-201','50%','30%','Valve'],['DV-101','50%','70%','Drain'],['V-202','82%','50%','Equipment']] as const;
  return <div className="grid gap-3 xl:grid-cols-[1fr_250px]"><div className="relative min-h-[440px] overflow-hidden rounded-xl border border-white/10 bg-[#071014] p-5"><div className="relative h-[360px]"><svg className="absolute inset-0 h-full w-full" aria-hidden="true"><line x1="17%" y1="50%" x2="50%" y2="30%" stroke="rgba(103,232,249,.45)" strokeWidth="2"/><line x1="17%" y1="50%" x2="50%" y2="70%" stroke="rgba(245,158,11,.5)" strokeWidth="2" strokeDasharray="6 5"/><line x1="50%" y1="30%" x2="82%" y2="50%" stroke="rgba(103,232,249,.4)" strokeWidth="2"/><line x1="50%" y1="70%" x2="82%" y2="50%" stroke="rgba(103,232,249,.18)" strokeWidth="2"/></svg>{nodes.map(([id,x,y,type]) => <button key={id} aria-label={`Select topology node ${id}`} onClick={() => onSelect(id)} className="absolute -translate-x-1/2 -translate-y-1/2" style={{left:x,top:y}}><div className={`flex h-16 w-28 flex-col items-center justify-center rounded-xl border transition ${selected===id?'border-cyan-300 bg-cyan-300/10 shadow-[0_0_30px_rgba(103,232,249,.12)]':'border-cyan-400/20 bg-[#0b171b] hover:border-cyan-400/40'}`}><span className="font-mono text-xs text-cyan-100">{id}</span><span className="text-[9px] uppercase tracking-wider text-zinc-600">{type}</span></div></button>)}</div><div className="flex flex-wrap gap-4 font-mono text-[9px] text-zinc-600"><span>━ accepted edge</span><span className="text-amber-200">┄ uncertainty retained</span><span>GraphStore view · read-only</span></div></div><AssetInspector selected={selected} onSelect={onSelect}/></div>;
}

function Findings({ findings, onSelect }: { findings: EngineeringFinding[]; onSelect?: (id: string) => void }) {
  const [filter, setFilter] = useState<'all'|'flags'|'observed'>('all');
  const visible = findings.filter(f => filter === 'all' || (filter === 'flags' ? f.reviewState === 'needs_verification' || f.reviewState === 'review' : f.reviewState === 'observed'));
  return <div className="overflow-hidden rounded-xl border border-white/10 bg-white/[.02]"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-white/10 px-4 py-3"><div className="flex gap-1">{(['all','flags','observed'] as const).map(f=><button key={f} onClick={()=>setFilter(f)} className={`rounded-md px-2.5 py-1.5 font-mono text-[8px] uppercase ${filter===f?'bg-cyan-300/10 text-cyan-200':'text-zinc-600 hover:text-zinc-300'}`}>{f}</button>)}</div><span className="font-mono text-[9px] text-zinc-600">{visible.length} records</span></div><div className="hidden grid-cols-[1fr_2fr_1.4fr_.7fr_1fr] border-b border-white/10 px-4 py-3 font-mono text-[9px] uppercase tracking-wider text-zinc-600 md:grid"><span>Asset</span><span>Claim</span><span>Source</span><span>Confidence</span><span>Review</span></div>{visible.map((f,i)=><button key={`${f.assetId}-${i}`} onClick={()=>onSelect?.(f.assetId)} className="grid w-full gap-2 border-b border-white/5 px-4 py-3 text-left last:border-0 md:grid-cols-[1fr_2fr_1.4fr_.7fr_1fr] md:items-center hover:bg-white/[.025]"><span className="font-mono text-[10px] text-cyan-200">{f.assetId}</span><span className="text-[10px] text-zinc-300">{f.claim}</span><span className="text-[10px] text-zinc-500">{f.source}</span><span className="font-mono text-[10px] text-zinc-400">{Math.round(f.confidence*100)}%</span><Pill tone={f.reviewState==='needs_verification'?'warn':f.reviewState==='observed'?'good':'neutral'}>{f.reviewState.replace('_',' ')}</Pill></button>)}</div>;
}

function Content({ active, selected, onSelect, findings, result, go }: { active: ViewId; selected: string; onSelect:(id:string)=>void; findings:EngineeringFinding[]; result:WorkbenchTaskResult|null; go:(v:ViewId)=>void }) {
  if(active==='pid') return <PIDWorkspace selected={selected} onSelect={onSelect}/>;
  if(active==='topology') return <TopologyWorkspace selected={selected} onSelect={onSelect}/>;
  if(active==='evidence') return <div className="space-y-4"><div className="flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-lg font-medium">Evidence ledger</h2><p className="mt-1 text-xs text-zinc-600">Claims remain tied to source and review state.</p></div><Pill tone="good"><ShieldCheck size={11}/> Provenance visible</Pill></div><Findings findings={findings} onSelect={id=>{onSelect(id);go('pid')}}/></div>;
  if(active==='artifact') return <div className="grid gap-4 lg:grid-cols-[1fr_320px]"><div className="rounded-xl border border-white/10 bg-white/[.02] p-6"><div className="mb-6 flex flex-wrap items-start justify-between gap-3"><div><div className="text-[9px] uppercase tracking-[.2em] text-cyan-300">Draft artifact</div><h2 className="mt-2 text-xl">P-101 Isolation Summary</h2></div><Pill tone="warn">Human review required</Pill></div><div className="space-y-3 text-sm text-zinc-400"><div className="rounded-lg border border-white/10 p-4"><b className="text-zinc-200">Finding</b><p className="mt-1">XV-201 is on the discharge path. Upstream suction isolation remains unresolved.</p></div><div className="rounded-lg border border-white/10 p-4"><b className="text-zinc-200">Evidence</b><p className="mt-1">{findings.length} evidence records are available for review.</p></div><div className="rounded-lg border border-amber-300/15 bg-amber-300/[.03] p-4 text-amber-100">Draft decision support only — not a permit, certification, or actuation command.</div></div></div><div className="rounded-xl border border-white/10 bg-[#071014] p-5"><div className="mb-4 font-mono text-[9px] uppercase tracking-[.2em] text-zinc-600">Export</div><button disabled className="flex w-full cursor-not-allowed items-center justify-between rounded-lg border border-white/10 px-3 py-3 text-xs text-zinc-500"><span>Prepare DOCX</span><Download size={14}/></button><p className="mt-3 text-[10px] leading-5 text-zinc-600">Generation is not simulated by the frontend.</p></div></div>;
  if(active==='document') return <div className="grid gap-3 md:grid-cols-2"><div className="rounded-xl border border-white/10 bg-white/[.02] p-5"><FileText size={16} className="text-cyan-300"/><h2 className="mt-4 text-base">Local document workspace</h2><p className="mt-2 text-xs leading-5 text-zinc-500">Ground answers in manuals, SOPs, inspection reports and correspondence inside the deployment boundary.</p></div><div className="rounded-xl border border-white/10 bg-white/[.02] p-5"><div className="font-mono text-[9px] uppercase tracking-wider text-zinc-600">Demo corpus</div><div className="mt-4 space-y-2">{['SOP · Isolation Procedure · local','Inspection Report · P-101 · local','P&ID Sheet 01 · local'].map(d=><button key={d} className="block w-full rounded-md border border-white/5 bg-black/20 px-3 py-2 text-left text-xs text-zinc-400 hover:text-zinc-200">{d}</button>)}</div></div></div>;
  if(active==='data') return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3">{[['Assets','5'],['Evidence',String(findings.length)],['Review flags',String(findings.filter(f=>f.reviewState!=='observed').length)]].map(([l,v])=><div key={l} className="rounded-xl border border-white/10 p-4"><span className="text-[9px] uppercase tracking-wider text-zinc-600">{l}</span><strong className={`mt-2 block text-2xl ${l==='Review flags'?'text-amber-200':''}`}>{v}</strong></div>)}</div><Findings findings={findings} onSelect={onSelect}/></div>;
  if(active==='engineering') return <div className="grid gap-4 lg:grid-cols-[1.25fr_.75fr]"><div className="rounded-xl border border-white/10 bg-white/[.02] p-6"><div className="flex items-center gap-2 text-[9px] uppercase tracking-[.2em] text-cyan-300"><GitBranch size={12}/> Engineering reasoning</div><h2 className="mt-3 text-xl">{selected}</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-400">Governed engineering tools combine visual evidence, topology and local documents. The model plans work; deterministic services remain the authority for structured engineering facts.</p><div className="mt-6 flex flex-wrap gap-2"><Pill tone="good"><Check size={10}/> Read-only</Pill><Pill>Evidence linked</Pill><Pill tone="warn">Verification retained</Pill></div></div><div className="rounded-xl border border-white/10 bg-[#071014] p-5"><div className="font-mono text-[9px] uppercase tracking-wider text-zinc-600">Current result</div><p className="mt-3 text-sm leading-6 text-zinc-300">{result?.summary ?? 'No task executed yet.'}</p></div></div>;
  return <div className="grid gap-4 lg:grid-cols-[1.3fr_.7fr]"><div className="rounded-xl border border-white/10 bg-white/[.02] p-6"><div className="flex items-center gap-2 text-[9px] uppercase tracking-[.2em] text-cyan-300"><Sparkles size={12}/> Workbench ready</div><h2 className="mt-3 text-2xl font-medium">What are you working on?</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-zinc-500">Use the agent for multi-step work, or open a workspace directly to inspect its evidence surface.</p><div className="mt-6 grid gap-2 sm:grid-cols-3">{(['engineering','pid','evidence'] as WorkspaceId[]).map(id=><button key={id} onClick={()=>go(id)} className="rounded-lg border border-white/10 bg-black/20 p-4 text-left hover:border-cyan-300/20"><div className="font-mono text-[9px] text-zinc-600">WORKSPACE</div><div className="mt-2 text-xs text-zinc-300">{WORKSPACES.find(w=>w.id===id)?.label}</div></button>)}</div></div><div className="rounded-xl border border-white/10 bg-[#071014] p-5"><div className="flex items-center gap-2 text-[9px] uppercase tracking-wider text-zinc-600"><Activity size={12}/> System boundary</div><div className="mt-4 space-y-3 text-xs text-zinc-400"><div className="flex justify-between"><span>Model</span><span className="text-zinc-300">Local / adapter-controlled</span></div><div className="flex justify-between"><span>Tools</span><span className="text-zinc-300">Governed</span></div><div className="flex justify-between"><span>Actuation</span><span className="text-emerald-200">None</span></div></div></div></div>;
}

export function WorkbenchV3({ onExit }: { onExit: () => void }) {
  const adapter = useMemo(() => getHRIDAYAdapter(), []);
  const adapterMode = getAdapterMode();
  const [active,setActive]=useState<ViewId>('overview'); const [selected,setSelected]=useState('P-101'); const [query,setQuery]=useState(''); const [palette,setPalette]=useState(false); const [taskState,setTaskState]=useState<TaskState>('idle'); const [result,setResult]=useState<WorkbenchTaskResult|null>(null); const [findings,setFindings]=useState<EngineeringFinding[]>([]); const [task,setTask]=useState(''); const [error,setError]=useState('');
  useEffect(()=>{let live=true; adapter.getEvidence(selected).then(v=>{if(live&&!result)setFindings(v)}).catch(()=>{if(live&&!result)setFindings([])}); return()=>{live=false}},[adapter,selected,result]);
  useEffect(()=>{const h=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();setPalette(true)}else if(e.key==='Escape'){setPalette(false)}};window.addEventListener('keydown',h);return()=>window.removeEventListener('keydown',h)},[]);
  const go=(v:ViewId)=>setActive(v);
  const runTask=async(q:string)=>{setTask(q);setQuery('');setPalette(false);setTaskState('running');setError('');try{const r=await adapter.runTask(q);setResult(r);setFindings(r.findings);setTaskState('complete');setActive(r.workspace)}catch(e){setTaskState('blocked');setError(e instanceof Error?e.message:'Task could not be completed.')}};
  const execute=()=>{const q=query.trim();if(!q)return;if(/analy|isola|prepare|check|trace|find sop|create/i.test(q))void runTask(q);else{const n=q.toLowerCase();go(n.includes('topo')?'topology':n.includes('pid')?'pid':n.includes('evid')?'evidence':n.includes('doc')?'document':n.includes('data')?'data':'overview');setPalette(false)}};
  const status=taskState==='running'?'Agent running':taskState==='complete'?'Task complete':taskState==='blocked'?'Task blocked':'Ready'; const tone=taskState==='complete'?'good':taskState==='blocked'?'warn':'neutral';
  return <div className="fixed inset-0 z-[100] flex flex-col overflow-hidden bg-[#05090b] text-white" style={{fontFamily:'inherit'}}><header className="flex h-14 shrink-0 items-center justify-between border-b border-white/10 bg-[#070c0f]/95 px-4 backdrop-blur-xl"><button onClick={onExit} aria-label="Return to product story" className="flex items-center gap-2"><div className="flex h-7 w-7 items-center justify-center rounded-md border border-cyan-300/30 bg-cyan-300/5 font-mono text-xs font-bold text-cyan-200">H</div><span className="text-sm font-semibold tracking-[.16em]">HRIDAY</span><span className="hidden text-[10px] uppercase tracking-[.22em] text-zinc-600 sm:block">Sovereign Industrial AI Workbench</span></button><div className="flex items-center gap-2"><button onClick={()=>setPalette(true)} className="hidden items-center gap-3 rounded-lg border border-white/10 bg-white/[.03] px-3 py-2 text-xs text-zinc-500 hover:text-zinc-200 md:flex"><Search size={13}/> Search or ask HRIDAY <kbd className="rounded border border-white/10 px-1.5 py-0.5 font-mono text-[9px]">⌘K</kbd></button><Pill tone={tone}><span className={`h-1.5 w-1.5 rounded-full ${taskState==='running'?'animate-pulse bg-cyan-300':taskState==='complete'?'bg-emerald-300':taskState==='blocked'?'bg-amber-300':'bg-zinc-500'}`}/>{status}</Pill></div></header>
    <div className="min-h-0 flex-1 overflow-y-auto"><div className="mx-auto max-w-[1500px] p-4 pb-24 md:p-6 md:pb-6"><div className="mb-5 flex items-end justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-[9px] uppercase tracking-[.22em] text-cyan-300"><Sparkles size={12}/> Contextual workspace</div><h1 className="text-xl font-medium md:text-2xl">{active==='overview'?'Mission control':WORKSPACES.find(w=>w.id===active)?.label}</h1></div><div className="hidden font-mono text-[9px] text-zinc-600 md:block">ADAPTER: {adapterMode.toUpperCase()} · READ-ONLY</div></div><WorkspaceNav active={active} onChange={go}/>
      <div className="mt-5 grid gap-5 lg:grid-cols-[320px_1fr]"><aside className="rounded-xl border border-white/10 bg-[#070c0f] p-4 lg:sticky lg:top-0 lg:h-fit"><div className="mb-4 flex items-center gap-2 text-[9px] font-semibold uppercase tracking-[.2em] text-zinc-600"><MessageSquare size={12}/> Conversation</div><div className="rounded-xl border border-white/10 bg-white/[.025] p-4"><div className="mb-2 flex items-center gap-2 text-[10px] text-cyan-300"><Bot size={13}/> HRIDAY Agent</div><p className="text-sm leading-6 text-zinc-300">{taskState==='running'?'Working through the requested task and collecting governed evidence…':taskState==='blocked'?'The task was blocked. No simulated backend result was substituted.':result?.summary??'Ask HRIDAY to analyze documents, trace equipment, inspect topology, or prepare evidence-backed artifacts.'}</p></div>{error&&<div role="alert" className="mt-3 rounded-lg border border-amber-300/20 bg-amber-300/[.04] p-3 text-[10px] leading-5 text-amber-100">{error}</div>}{task&&<div className="mt-3 rounded-lg border border-white/10 bg-black/20 p-3"><div className="mb-1 font-mono text-[8px] uppercase tracking-wider text-zinc-600">Current task</div><p className="text-xs text-zinc-400">{task}</p></div>}<div className="mt-4 space-y-2"><div className="mb-2 font-mono text-[8px] uppercase tracking-wider text-zinc-600">Quick tasks</div>{QUICK_TASKS.map(q=><button key={q} disabled={taskState==='running'} onClick={()=>void runTask(q)} className="group flex w-full items-center justify-between rounded-lg border border-white/10 bg-white/[.02] px-3 py-3 text-left text-[10px] text-zinc-300 hover:border-cyan-400/25 disabled:opacity-50"><span>{q}</span><ArrowRight size={12} className="text-zinc-600 group-hover:text-cyan-300"/></button>)}</div></aside><main className="min-w-0"><AnimatePresence mode="wait"><motion.div key={active} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,y:-6}} transition={{duration:.2}}><Content active={active} selected={selected} onSelect={setSelected} findings={findings} result={result} go={go}/></motion.div></AnimatePresence></main></div>
      <div className="mt-5 flex flex-col gap-3 rounded-xl border border-white/10 bg-[#070c0f] p-3 md:flex-row md:items-center"><div className="flex items-center gap-2 px-2 text-[9px] uppercase tracking-wider text-zinc-600"><Activity size={12}/> Agent loop</div><div className="flex flex-1 items-center gap-2 overflow-x-auto">{['Intent','Plan','Tools','Observe','Evidence','Answer'].map((s,i)=>{const on=taskState==='running'?i<4:taskState==='complete';return <div key={s} className={`flex shrink-0 items-center gap-2 rounded-md border px-2.5 py-2 text-[9px] ${on?'border-cyan-300/20 bg-cyan-300/5 text-cyan-200':'border-white/5 text-zinc-600'}`}><span className="font-mono">0{i+1}</span>{s}{i<5&&<ChevronRight size={10}/>}</div>})}</div></div><div className="mt-3 flex flex-col gap-2 rounded-lg border border-white/10 bg-black/20 px-4 py-3 text-[9px] text-zinc-600 sm:flex-row sm:items-center sm:justify-between"><span><ShieldCheck size={11} className="mr-2 inline"/>{adapterMode==='demo'?'DEMO CLOUD INSTANCE — NOT AIR-GAPPED':'LOCAL DEPLOYMENT — SOVEREIGNTY TELEMETRY REQUIRED'}</span><span>Physical/network air-gapping remains an infrastructure control.</span></div></div></div>
    <nav aria-label="Mobile workspaces" className="fixed bottom-0 left-0 right-0 z-[110] border-t border-white/10 bg-[#070c0f]/95 p-2 backdrop-blur-xl lg:hidden"><div className="flex gap-1 overflow-x-auto">{[{id:'overview' as ViewId,label:'Home'},...WORKSPACES.map(w=>({id:w.id,label:w.label}))].map(({id,label})=><button key={id} onClick={()=>go(id)} className={`shrink-0 rounded-md px-3 py-2 text-[9px] font-medium ${active===id?'bg-cyan-300/10 text-cyan-200':'text-zinc-500'}`}>{label}</button>)}</div></nav>
    <AnimatePresence>{palette&&<motion.div role="dialog" aria-modal="true" aria-label="HRIDAY command palette" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="fixed inset-0 z-[120] flex items-start justify-center bg-black/70 p-4 pt-[12vh] backdrop-blur-sm" onMouseDown={e=>{if(e.target===e.currentTarget)setPalette(false)}}><motion.div initial={{opacity:0,y:-12,scale:.98}} animate={{opacity:1,y:0,scale:1}} className="w-full max-w-2xl overflow-hidden rounded-xl border border-white/10 bg-[#0a1115] shadow-2xl"><div className="flex items-center gap-3 border-b border-white/10 px-4"><Command size={15} className="text-cyan-300"/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')execute()}} placeholder="Search a workspace or ask HRIDAY to do something…" className="h-14 flex-1 bg-transparent text-sm text-white outline-none placeholder:text-zinc-600"/><button onClick={()=>setPalette(false)} aria-label="Close command palette"><X size={15} className="text-zinc-600"/></button></div><div className="p-3"><div className="px-2 py-2 font-mono text-[8px] uppercase tracking-wider text-zinc-600">Suggested actions</div>{QUICK_TASKS.map(q=><button key={q} onClick={()=>void runTask(q)} className="flex w-full items-center justify-between rounded-lg px-3 py-3 text-left text-xs text-zinc-300 hover:bg-white/[.04]"><span>{q}</span><ArrowRight size={13} className="text-zinc-600"/></button>)}</div></motion.div></motion.div></AnimatePresence>
  </div>;
}
